#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# BYOG: the user geometry named in system/snappyHexMeshDict must already be
# present in constant/triSurface/ before meshing.
runApplication surfaceFeatures
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication $(getApplication)

#------------------------------------------------------------------------------
